# This workflow will build a Spring Boot project with Java and Maven

name: Spring Boot / Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  check:
    runs-on: ubuntu-latest
    name: Checking dependencies...
    steps:
      - uses: actions/checkout@v3

      - name: OWASP Dependency Check
        run: mvn dependency-check:check

  compile:
    runs-on: ubuntu-latest
    name: Compiling project...
    needs: check
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Compile Code
        run: mvn compile

  test:
    runs-on: ubuntu-latest
    name: Running tests...
    needs: compile
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run Unit Tests
        run: mvn test

  build:
    runs-on: ubuntu-latest
    name: Building project...
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Project using Maven
        run: mvn -B package --file pom.xml